[project]
name = "djnago-rest-hrm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.17",
    "djangorestframework>=3.18.0",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.30.0",
    "requests>=2.34.2",
    "pillow>=12.3.0",
    "psycopg>=3.3.4",
    "uvicorn>=0.52.3",
    "python-decouple>=3.8",
    "pyzk>=0.9",
    "rich>=15.0.0",
    "django-filter>=26.1",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=8.0.0",
    "ipdb>=0.13.13",
    "pre-commit>=4.6.2",
    "rich>=15.0.0",
]
