# Generated by Django 6.1 on 2026-08-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="zk_device_user_id",
            field=models.CharField(db_index=True, default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
