# Generated by Django 6.1 on 2026-08-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_employee_zk_device_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="zk_device_user_id",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
    ]
