# Generated by Django 6.1 on 2026-09-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_employee_zk_device_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
