# Generated by Django 6.1 on 2026-09-06 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.leave.models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeLeaveBalance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField(default=apps.leave.models.get_current_year)),
                ("allocated_days", models.PositiveIntegerField(default=0, help_text="Total days granted for this leave type for the year.")),
                (
                    "employee",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leave_balances", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "leave_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="employee_balances", to="leave.leavetype"),
                ),
            ],
            options={
                "ordering": ["-year", "employee", "leave_type"],
                "unique_together": {("employee", "leave_type", "year")},
            },
        ),
    ]
