# Generated by Django 6.1 on 2026-08-25 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAttendanceLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("total_hours", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("present", "Present"), ("late", "Late"), ("absent", "Absent"), ("half_day", "Half Day")],
                        default="absent",
                        max_length=20,
                    ),
                ),
                ("is_late", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="daily_attendance_logs", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [models.UniqueConstraint(fields=("employee", "date"), name="unique_employee_date")],
            },
        ),
        migrations.CreateModel(
            name="DeviceAttendanceLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_serial", models.CharField(max_length=50)),
                ("punch_time", models.DateTimeField(db_index=True)),
                (
                    "punch_type",
                    models.CharField(
                        choices=[("0", "Check In"), ("1", "Check Out"), ("2", "Break Out"), ("3", "Break In"), ("4", "OT In"), ("5", "OT Out")],
                        max_length=10,
                    ),
                ),
                (
                    "verify_mode",
                    models.CharField(blank=True, choices=[("1", "Fingerprint"), ("4", "Card"), ("15", "Face")], max_length=20, null=True),
                ),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendance_logs", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-punch_time"],
                "indexes": [models.Index(fields=["employee", "punch_time"], name="attendance__employe_7e7e7a_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("employee", "punch_time", "device_serial"), name="unique_employee_punch_per_device")
                ],
            },
        ),
    ]
