# Generated by Django 6.1 on 2026-08-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deviceattendancelog",
            name="unique_employee_punch_per_device",
        ),
        migrations.RemoveIndex(
            model_name="deviceattendancelog",
            name="attendance__employe_7e7e7a_idx",
        ),
        migrations.AddField(
            model_name="deviceattendancelog",
            name="device_user_id",
            field=models.CharField(default="UNKNOWN", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deviceattendancelog",
            name="punch",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deviceattendancelog",
            name="status",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deviceattendancelog",
            name="uid",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="deviceattendancelog",
            constraint=models.UniqueConstraint(fields=("device_serial", "device_user_id", "punch_time"), name="unique_device_attendance"),
        ),
        migrations.RemoveField(
            model_name="deviceattendancelog",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="deviceattendancelog",
            name="punch_type",
        ),
        migrations.RemoveField(
            model_name="deviceattendancelog",
            name="raw_payload",
        ),
        migrations.RemoveField(
            model_name="deviceattendancelog",
            name="verify_mode",
        ),
    ]
