# Generated by Django 6.1 on 2026-08-30 15:04

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_remove_deviceattendancelog_unique_employee_punch_per_device_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("serial", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                ("port", models.IntegerField(default=4370)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SyncState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_serial", models.CharField(max_length=50, unique=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="deviceattendancelog",
            name="uid",
        ),
        migrations.AlterField(
            model_name="dailyattendancelog",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("late", "Late"),
                    ("absent", "Absent"),
                    ("half_day", "Half Day"),
                    ("missing_check_out", "Missing Check Out"),
                    ("less than half day", "Less Than Half Day"),
                ],
                default="absent",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("single_column", models.BooleanField(default=True, editable=False, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("check_in_time", models.TimeField(default="09:00")),
                ("check_out_time", models.TimeField(default="17:00")),
                ("late_threshold_minutes", models.PositiveIntegerField(default=15)),
                ("half_day_threshold_hours", models.DecimalField(decimal_places=2, default=4, max_digits=4)),
                ("full_day_hours", models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ("tax_percentage", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5)),
                ("overtime_enabled", models.BooleanField(default=True)),
                ("overtime_multiplier", models.DecimalField(decimal_places=2, default=Decimal("1.50"), max_digits=5)),
                ("late_deduction_enabled", models.BooleanField(default=False)),
                ("late_deduction_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("grace_period_minutes", models.PositiveIntegerField(default=0)),
                ("minimum_working_days", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [models.CheckConstraint(condition=models.Q(("single_column", True)), name="system_policy_singleton_true")],
            },
        ),
    ]
