# Generated by Django 6.1 on 2026-08-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_device_syncstate_remove_deviceattendancelog_uid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyattendancelog",
            name="early_leave_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyattendancelog",
            name="is_early_leave",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="policy",
            name="early_leave_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dailyattendancelog",
            name="status",
            field=models.CharField(blank=True, choices=[("present", "Present"), ("half_day", "Half Day")], max_length=20, null=True),
        ),
    ]
