# Generated by Django 6.1 on 2026-09-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_dailyattendancelog_early_leave_minutes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policy",
            name="early_leave_minutes",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="grace_period_minutes",
        ),
    ]
