# Generated by Django 6.1 on 2026-09-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_remove_policy_early_leave_minutes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyattendancelog",
            name="status",
            field=models.CharField(
                blank=True, choices=[("present", "Present"), ("half_day", "Half Day"), ("absent", "Absent")], max_length=20, null=True
            ),
        ),
    ]
