# Generated by Django 6.1 on 2026-09-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_alter_dailyattendancelog_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyattendancelog",
            name="status",
            field=models.CharField(blank=True, choices=[("present", "Present"), ("half_day", "Half Day")], max_length=20, null=True),
        ),
    ]
